name: Docker Image CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Compile with Webpacker
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn upgrade
          bundle exec rails webpacker:install
          bundle exec rails webpacker:compile
        env:
          NODE_ENV: production
      - name: Build the Docker image
        run: docker-compose build
      - name: docker-compose up
        run: |
          docker-compose down
          docker-compose up -d
          sleep 10
          docker-compose exec -T web bash -c "rails db:migrate:reset RAILS_ENV=test"
          docker-compose exec -T web bash -c "rails db:seed RAILS_ENV=test"
      #      - name: Rails-test
      #        run: docker-compose exec -T web bash -c "rails test"
      - name: Configure AWS Credentials # AWSアクセス権限設定
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR # ECRログイン処理
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR # ECRイメージPush
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        run: |
          IMAGE_TAG=latest
          APP_NAME=rails-app_web
          docker tag $APP_NAME $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Render migration task definition # ECSタスク定義ファイルレンダリング
        id: render-migration-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: aws/task-definition.json # レポジトリ以下のタスク定義ファイルがあるPath
          container-name: migration-web
          image: 282706015608.dkr.ecr.ap-northeast-1.amazonaws.com/rails-app:latest
      - name: Modify Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-migration-web-container.outputs.task-definition }}
          container-name: web
          image: 282706015608.dkr.ecr.ap-northeast-1.amazonaws.com/rails-app:latest

      - name: Deploy to Amazon ECS service # ECSサービスデプロイ
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: rails-app-service
          cluster: rails-app-cluster

